### ISSUE TITLE
IP to VPN provider lookup

### ISSUE THREAD

**Issue by alessandromrc** [SwoopSolutions/Soup#27]
I'm thinking that a way to detect the "hosting" service for VPNs would be cool and so I made up a list of all Mullvad IP addresses that could be used to reverse an IP address to the service name.

I'm attaching the IP addresses list below:

[ips.txt](https://github.com/calamity-inc/Soup/files/9740285/ips.txt)
[ips6.txt](https://github.com/calamity-inc/Soup/files/9740294/ips6.txt)

**Comment by Sainan** [comment]
I did think that might be a cool bit of info, but just hardcoding the IPs isn't a long-term solution, and it wouldn't be very useful for only a single VPN provider.

**Comment by alessandromrc** [comment]
This could be a better way for Mullvad anyway:
https://ipv4.am.i.mullvad.net/json

**Comment by alessandromrc** [comment]
This could be a better way for Mullvad:
https://api.mullvad.net/www/relays/all/

Still, calling mullvad backend every time isn't that great

**Comment by Sainan** [comment]
Idk what you mean by "every time." This data can be cached for at least 24 hours.

**Comment by alessandromrc** [comment]
It can surely be cached, the problems comes if a big number of users will start their lookup at the same time for the first time

**Comment by Sainan** [comment]
Idk if Soup is the client or server in your hypothetical. Also not really a problem for us. ;P

**Comment by alessandromrc** [comment]
I don't even use Soup for any project actually, just contributing for fun :)

**Comment by alessandromrc** [comment]
JSON server list for NordVPN:

https://api.nordvpn.com/server

**Comment by Sainan** [comment]
No IPv6? :megamind:

**Comment by alessandromrc** [comment]
> No IPv6? :megamind:

Seems so 🗿💀

**Comment by Sainan** [comment]
I think this is out-of-scope for Soup. It's clear that a separate project is needed that crawls various VPN providers and then distributes a combined table. If such a thing exists, Soup might add support for loading said table.
